# Generated by Django 4.2 on 2023-04-23 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='nom',
            field=models.CharField(max_length=50),
        ),
    ]
