# Generated by Django 4.2 on 2023-05-08 12:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0004_gallerie'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gallerie',
            name='slug',
        ),
    ]
