# Generated by Django 4.2 on 2023-05-08 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0005_remove_gallerie_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='gallerie',
            name='nom',
            field=models.CharField(default='Image', max_length=50),
        ),
        migrations.AddField(
            model_name='gallerie',
            name='slug',
            field=models.SlugField(default='slug'),
        ),
    ]
