# Generated by Django 4.2 on 2023-05-10 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Store', '0006_gallerie_nom_gallerie_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categorie',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(max_length=50)),
                ('slug', models.SlugField(blank=True, max_length=500, null=True, unique=True)),
            ],
        ),
        migrations.RenameField(
            model_name='gallerie',
            old_name='images',
            new_name='image',
        ),
        migrations.CreateModel(
            name='Benin_Mobilier',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nom', models.CharField(default='Image', max_length=50)),
                ('slug', models.SlugField(default='slug')),
                ('image', models.ImageField(blank=True, null=True, upload_to='')),
                ('categorie', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Store.categorie')),
            ],
        ),
    ]
